### ISSUE TITLE
MANIFEST.in

### ISSUE THREAD

**Issue by thewchan** [MatteoGuadrini/pyreports#1]
Can a MANIFEST.in file be added?  https://packaging.python.org/guides/using-manifest-in/

**Comment by MatteoGuadrini** [comment]
Hi @thewchan,
in the manifest file you can write additional files that should be _added_ or _removed_ from the installation during the execution of the `setup` function.
There are no additional files expected in this package; Did you notice any missing or too many files that should be removed?

Can you be more specific in the request?
Thanks in advance

**Comment by thewchan** [comment]
Sure thing! Thanks for the response. I'm trying to get this package onto conda forge conda-forge.org/, and the binaries are failing to build because of the lack of a MANIFEST.in file. Specifically, the sdist seems to not include the `__info__` module (though I see it in the repo.) Does that help?

**Comment by MatteoGuadrini** [comment]
I have committed right now with the indicated file, including the `__info__` module as you suggested.
Thanks for your help @thewchan

**Comment by thewchan** [comment]
Thanks so much, once this is pushed to a new release I can resume the attempt to get this package on conda forge.
